### ISSUE TITLE
Pugdebug error

### ISSUE THREAD

**Issue by StephanKrauss** [Mte90/pugdebug#15]
Hello,

i work with pugdebug under windows 10.
When i 'start listening' i get a error mesage.
-------------------------
Der Zugriff auf einen Socket war aufgrund der Zugriffsrechte des Sockets unzulässig

Access to a socket was not permitted due to the access rights of the socket
-----------------------

Who can help ?

Your sincerly

Stephan

**Comment by andreym333** [comment]
Try to temporarily disable your firewall.

**Comment by Mte90** [comment]
Are you using this pugdebug or the original one?
Where are you getting this error in the UI of pugdebug?
Where is the domain with xdebug in a VM?

And yes try with the firewall disabled on windows.
