### ISSUE TITLE
Debugging connection

### ISSUE THREAD

**Issue by starboy4** [Mte90/pugdebug#17]
Hi there, 

I can't get the debugging connection started with pugdebug because it says waiting for connection. I am debugging on windows with localhost, local website and xdebug. I have the project folder selected and loaded in the file browser. 

I can get the xdebug session from my browser to phpstorm and other IDEs but not pugdebug. 

Does anyone know what am I doing wrong, or am I missing on something. 

Kind regards,

**Comment by Mte90** [comment]
This happens on settings of pugdebug that are not configured rightly on the project. Did you checked there if the parameters are right?

**Comment by starboy4** [comment]
Hi,
Thanks for the support. I get an error saying "getaddrinfo failed". Could that be the reason? 
Thanks

**Comment by Mte90** [comment]
Can I have a screen where the error is happening?
Basically is saying that the address and port are not responding so maybe they are wrong in your settings and you need to change them.

**Comment by starboy4** [comment]
Thanks for helping Daniele  👍
