### ISSUE TITLE
Update changelog

### ISSUE THREAD

**Issue by Mte90** [Mte90/pugdebug#3]
I saw more commites, cool!
Can you update the https://github.com/Mte90/pugdebug/blob/master/CHANGELOG.md with the latest more important changes?
So when we will release the new version everything is ready.

**Comment by andreym333** [comment]
I will change it a bit later.

**Comment by Mte90** [comment]
perfect, I will leave this ticket opened as remainder :-D

**Comment by andreym333** [comment]
Changelog has been updated: 8ff1872

**Comment by Mte90** [comment]
Perfect, do you think it is the case to do a new release or you are planning to do more changes?

**Comment by andreym333** [comment]
I'm planning to do a lot more changes :smiley:

**Comment by Mte90** [comment]
Ok so let's open few tickets about the changes that you want to do, just to follow the development :-D

**Comment by andreym333** [comment]
I pushed a few new commits. Nothing really interesting, mainly bug fixes. The line numbers widget has also been significantly redesigned.
