### ISSUE TITLE
Update all the code license sections in top of all the files

### ISSUE THREAD

**Issue by Mte90** [Mte90/pugdebug#7]
As example in 
https://github.com/Mte90/pugdebug/blob/master/pugdebug/gui/breakpoints.py#L3

There is a comment section that need to be changed as:

```
    pugdebug - a standalone PHP debugger
    =========================
    copyright: (c) 2015 Robert Basic and fork's contributors
    license: GNU GPL v3, see LICENSE for more details
``` 

I am wondering if lines as:

`__author__ = "robertbasic"`

Can removed from all the files because they are unused

**Comment by TseChapman** [comment]
Hello @Mte90 , this my first time try to contribute to open source. I think your issue is a good first try for me. May I be assigned for this issue?

Also, I have a question for this issue. I just need to change the license section for all .py or Python file right?

**Comment by Mte90** [comment]
Hi @TseChapman, yes you need to change all the .py files that have this similar text.

About assigning, on GitHub I can do it if I add you in the repo but as it is your first contribution I prefer to not do it. Anyway I will keep that ticket for you.

**Comment by TseChapman** [comment]
Ok, I will push after changing the license section. Thank you.

**Comment by TseChapman** [comment]
I will remove the __author__ = "robertbasic" as well

**Comment by TseChapman** [comment]
I upload a pull request

**Comment by Mte90** [comment]
merged thanks!
